PARAMS = {
	'country_list': [
		'albania',
		 'antigua and barbuda',
		 'argentina',
		 'armenia',
		 'aruba',
		 'australia',
		 'austria',
		 'azerbaijan',
		 'bahamas',
		 'bahrain',
		 'barbados',
		 'belarus',
		 'belgium',
		 'belize',
		 'bosnia and herzegovina',
		 'brazil',
		 'bulgaria',
		 'cabo verde',
		 'canada',
		 'chile',
		 'colombia',
		 'costa rica',
		 'croatia',
		 'cuba',
		 'cyprus',
		 'czech republic',
		 'denmark',
		 'dominica',
		 'ecuador',
		 'el salvador',
		 'estonia',
		 'fiji',
		 'finland',
		 'france',
		 'georgia',
		 'germany',
		 'greece',
		 'grenada',
		 'guatemala',
		 'guyana',
		 'hungary',
		 'iceland',
		 'ireland',
		 'israel',
		 'italy',
		 'jamaica',
		 'japan',
		 'kazakhstan',
		 'kiribati',
		 'kuwait',
		 'kyrgyzstan',
		 'latvia',
		 'lithuania',
		 'luxembourg',
		 'macau',
		 'maldives',
		 'malta',
		 'mauritius',
		 'mexico',
		 'mongolia',
		 'montenegro',
		 'netherlands',
		 'new zealand',
		 'nicaragua',
		 'norway',
		 'oman',
		 'panama',
		 'paraguay',
		 'philippines',
		 'poland',
		 'portugal',
		 'puerto rico',
		 'qatar',
		 'republic of korea',
		 'romania',
		 'russian federation',
		 'saint kitts and nevis',
		 'saint lucia',
		 'saint vincent and grenadines',
		 'san marino',
		 'serbia',
		 'seychelles',
		 'singapore',
		 'slovakia',
		 'slovenia',
		 'south africa',
		 'spain',
		 'sri lanka',
		 'suriname',
		 'sweden',
		 'switzerland',
		 'thailand',
		 'trinidad and tobago',
		 'turkey',
		 'turkmenistan',
		 'ukraine',
		 'united arab emirates',
		 'united kingdom',
		 'united states',
		 'uruguay',
		 'uzbekistan'
		],
	'age_list': age_ranger,
}

def age_ranger(age: int) -> str:
    if (age >=5) & (age < 15):
        return 1
    elif (age >=15) & (age < 25):
        return 2
    elif (age >=25) & (age < 35):
        return 3
    elif (age >=35) & (age < 55):
        return 4
    elif (age >=55) & (age < 75):
        return 5
    elif age >=75:
        return 6
    else:
        raise ValueError('Age too low.')
