PARAMS = {
	'country_list': {'albania': 1,
			 'antigua and barbuda': 2,
			 'argentina': 3,
			 'armenia': 4,
			 'aruba': 5,
			 'australia': 6,
			 'austria': 7,
			 'azerbaijan': 8,
			 'bahamas': 9,
			 'bahrain': 10,
			 'barbados': 11,
			 'belarus': 12,
			 'belgium': 13,
			 'belize': 14,
			 'bosnia and herzegovina': 15,
			 'brazil': 16,
			 'bulgaria': 17,
			 'cabo verde': 18,
			 'canada': 19,
			 'chile': 20,
			 'colombia': 21,
			 'costa rica': 22,
			 'croatia': 23,
			 'cuba': 24,
			 'cyprus': 25,
			 'czech republic': 26,
			 'denmark': 27,
			 'dominica': 28,
			 'ecuador': 29,
			 'el salvador': 30,
			 'estonia': 31,
			 'fiji': 32,
			 'finland': 33,
			 'france': 34,
			 'georgia': 35,
			 'germany': 36,
			 'greece': 37,
			 'grenada': 38,
			 'guatemala': 39,
			 'guyana': 40,
			 'hungary': 41,
			 'iceland': 42,
			 'ireland': 43,
			 'israel': 44,
			 'italy': 45,
			 'jamaica': 46,
			 'japan': 47,
			 'kazakhstan': 48,
			 'kiribati': 49,
			 'kuwait': 50,
			 'kyrgyzstan': 51,
			 'latvia': 52,
			 'lithuania': 53,
			 'luxembourg': 54,
			 'macau': 55,
			 'maldives': 56,
			 'malta': 57,
			 'mauritius': 58,
			 'mexico': 59,
			 'mongolia': 60,
			 'montenegro': 61,
			 'netherlands': 62,
			 'new zealand': 63,
			 'nicaragua': 64,
			 'norway': 65,
			 'oman': 66,
			 'panama': 67,
			 'paraguay': 68,
			 'philippines': 69,
			 'poland': 70,
			 'portugal': 71,
			 'puerto rico': 72,
			 'qatar': 73,
			 'republic of korea': 74,
			 'romania': 75,
			 'russian federation': 76,
			 'saint kitts and nevis': 77,
			 'saint lucia': 78,
			 'saint vincent and grenadines': 79,
			 'san marino': 80,
			 'serbia': 81,
			 'seychelles': 82,
			 'singapore': 83,
			 'slovakia': 84,
			 'slovenia': 85,
			 'south africa': 86,
			 'spain': 87,
			 'sri lanka': 88,
			 'suriname': 89,
			 'sweden': 90,
			 'switzerland': 91,
			 'thailand': 92,
			 'trinidad and tobago': 93,
			 'turkey': 94,
			 'turkmenistan': 95,
			 'ukraine': 96,
			 'united arab emirates': 97,
			 'united kingdom': 98,
			 'united states': 99,
			 'uruguay': 100,
			 'uzbekistan': 101},
	'age_list': age_ranger,
	'sex_list': {'male': 0,
		     'female': 1
		    }
}

def age_ranger(age: int) -> str:
    if (age >=5) & (age < 15):
        return 1
    elif (age >=15) & (age < 25):
        return 2
    elif (age >=25) & (age < 35):
        return 3
    elif (age >=35) & (age < 55):
        return 4
    elif (age >=55) & (age < 75):
        return 5
    elif age >=75:
        return 6
    else:
        raise ValueError('Age too low.')
