version: "2.10"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    links:
        - server
  server:
    build: ./mlflow_server
    ports:
      - "5000:5000"
    network_mode: host
    command: mlflow server --backend-store-uri mysql://localhost:5432 --default-artifact-root ./mlruns
  client:
    build: ./mlflow_regression
    network_mode: host
    depends_on:
      - server
    tty: true
volumes:
  db:
    driver: local