version: "2.10"
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  server:
    build: ./mlflow_server
    ports:
      - "5000:5000"
    network_mode: host
    command: mlflow server --backend-store-uri mysql://localhost:5432 --default-artifact-root ./mlruns
  client:
    build: ./mlflow_regression
    network_mode: host
    depends_on:
      - server
    tty: true
volumes:
  db:
    driver: local