version: "2.10"
services:
  server:
    build: ./mlflow_server
    ports:
      - "5000:5000"
    network_mode: host
    command: mlflow server --backend-store-uri postgresql://localhost:5432 --default-artifact-root ./mlruns
  client:
    build: ./mlflow_regression
    network_mode: host
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    network_mode: host
