name: model-actual-tree
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd data_governance_hw/
          pip3 install -r requirements.txt
          python3 forest_model.py rf standard
          cat metrics.txt >> report.md
          cml publish feature_importance.png --md >> report.md
          cml send-comment report.md
