name: model-actual-tree
on:
  push:
    branches:
     - 'experiment'
permissions:
  contents: write
  actions: write
  issues: write

jobs:
  data_governance:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data_governance_hw/forest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET+ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source ./bin/activate
          python -m pip install -r requirements.txt
          dvc pull train.csv --run-cache
          black *.py
          pylint *.py
          python forest_model.py rf standard
          deactivate
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          echo "## Model metrics:" > report.md
          cat metrics.txt >> report.md
          cml publish feature_importance.png --md >> report.md
          cml send-comment report.md
